services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cr8s
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: ${SERVER_IMAGE:-cr8s-server-dev:latest}
    pull_policy: never
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ${SERVER_DEBUG_ARGS:-}
    environment:
      ROCKET_PROFILE: default
      DATABASE_URL: postgres://postgres:secret@postgres:5432/cr8s
      REDIS_URL: redis://redis:6379/
      RUST_BACKTRACE: 1
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/cr8s/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  cli:
    image: ${CLI_IMAGE:-cr8s-cli-dev:latest}
    pull_policy: never
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres:5432/cr8s
      REDIS_URL: redis://redis:6379/
    profiles:
      - tools  # Optional: only start when explicitly requested
