services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cr8s
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    image: ghcr.io/johnbasrai/cr8s/cr8s-server:v0.3.1  # ← pulled or loaded locally
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      ROCKET_PROFILE: default
      DATABASE_URL: postgres://postgres:secret@postgres:5432/cr8s
    ports:
      - "8000:8000"
