
services:
  postgres:
    image: postgres:15
    networks:
      - cr8s-net
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 2s
      retries: 10

  redis:
    image: redis:7
    networks:
      - cr8s-net
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    networks:
      - cr8s-net
    image: ghcr.io/johnbasrai/cr8s/rust-runtime:latest
    restart: unless-stopped
    environment:
      ROCKET_ENV: development
      ROCKET_ADDRESS: 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/johnbasrai/cr8s/rust-dev:latest
    networks:
      - cr8s-net
    command: sleep infinity
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:secret@postgres:5432/cr8s
      ROCKET_ENV: development
    depends_on:
      - postgres
      - redis

networks:
  cr8s-net:
    external: true
